### ISSUE TITLE
Open Source Licenses?

### ISSUE THREAD

**Issue by davedittrich** [larsks/dockerize#4]
Hi Lars,

It is really cool that you are producing so many open source tools. I don't see any license with them, however, so it will limit how much the code can be used in other projects. Could you add an open source license, perhaps Berkeley Three Clause or Public Domain, which are very compatible with open source projects? Take a look at these pages for information about selecting and including copyright and license statements.

https://www.jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/
http://www.groklaw.net/article.php?story=20031231092027900
http://www.pydanny.com/cookie-project-templates-made-easy.html
https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29

Thanks again and keep up the good work!

Dave

**Comment by larsks** [comment]
As part of the recent packaging for PyPi I added a license file to the distribution.
