### ISSUE TITLE
any plans for a versioned release?

### ISSUE THREAD

**Issue by codemedic** [larsks/dockerize#6]

**Comment by larsks** [comment]
You mean like https://pypi.python.org/pypi/dockerize ?

**Comment by codemedic** [comment]
I meant tagging releases on github.

**Comment by codemedic** [comment]
@larsks I did not realise there is a pip package for this.
I was pulling using git, as done in github.com/redmatter/docker-dockerize

Would it be possible to drive pip packaging using github tags / releases ?
