### ISSUE TITLE
Workingdir

### ISSUE THREAD

**Issue by carlochess** [larsks/dockerize#9]
I think that the default working dir of the image dockerize create is '/', can we add an optional argument like

`optional arguments:
  -w, --wd            change the working dir

And then, in the dockerfile

`FROM scratch
COPY . /
WORKDIR /home/great/music/

ENTRYPOINT ["/bin/bash"]
`
Thanks in advance

**Comment by larsks** [comment]
You're welcome to submit a patch for the above, although in general I would probably just specify the working dir via the `-w` option to `docker run`.

**Comment by carlochess** [comment]
That's a great idea. Thanks man!
